### PR TITLE
JS ctags refinements

### PR DESCRIPTION
**Pull request by brettz9**
The following was adapted from https://gist.github.com/tim-smart/199338

1. Distinctly label variables, constants, and individual JavaScript types
1. Change getter/setter to own list type separate from function/class/method
1. Support one-character length identifiers
1. Avoid switch in apparent regex for inline functions (not so sure about the legitimacy of this entire line though: `--regex-JavaScript=/(,|^|\*\/)[ \t]*(while|if|for|switch|function|([A-Za-z_$][A-Za-z0-9_$]*))[ \t]*\([^)]*\)[ \t]*\{/\3/,function/`
1. For identifiers, avoid matching if begin with digit
1. Avoid duplication of function/method/class regexes given built-in parsing

### CODE REVIEW

**Comment by brettz9** [comment]
Another useful addition would be:

`--regex-JavaScript=/(,|(;|^)[ \t]*(var|let|([A-Za-z_$][A-Za-z0-9_$.]*\.)+))[ \t]*([A-Za-z_$][A-Za-z0-9_$.]*)[ \t]*=[ \t]*[^tfn0-9"'{\[]+([,;=]|$)/\5/,unknown/`

It is a little imperfect, however, as I had to overcome the regex engine allowing negative lookahead, so I disallowed 't' (for `true`), 'f' (for `false` or `function`), and 'n' (for `null) to avoid displaying these. One can remove those characters to err on the side of caution, but there will be duplicates if one also has enabled the boolean, function, or null types.

These additions would also be useful:
```
--regex-JavaScript=/(,|(;|^)[ \t]*(var|let|const|([A-Za-z_$][A-Za-z0-9_$.]*\.)+))[ \t]*([A-Za-z_$][A-Za-z0-9_$.]*)[ \t]*=[ \t]*null/\5/,null/
--regex-JavaScript=/(,|(;|^)[ \t]*(var|let|const|([A-Za-z_$][A-Za-z0-9_$.]*\.)+))[ \t]*([A-Za-z_$][A-Za-z0-9_$.]*)[ \t]*=[ \t]*undefined/\5/,undefined/
```
...and changing the variable definition to `undefined`:
--regex-JavaScript=/(,|(;|^)[ \t]*(var|let|([A-Za-z_$][A-Za-z0-9_$.]*\.)+))[ \t]*([A-Za-z_$][A-Za-z0-9_$.]*)[ \t]*[ \t]*([,;]|$)/\5/,undefined/

Note that the preceding does not distinguish declared variables in a list from function parameters, however.

**Comment by brettz9** [comment]
And this expanded array to catch non-literal arrays as well:

`--regex-JavaScript=/(,|(;|^)[ \t]*(var|let|const|([A-Za-z_$][A-Za-z0-9_$.]*\.)+))[ \t]*([A-Za-z_$][A-Za-z0-9_$.]*)[ \t]*=[ \t]*(\[|(new[ \t]+)?Array\()/\5/,array/`

**Comment by brettz9** [comment]
And to get more granularity in the built-in functions, one can instead use the following (being careful to deselect the existing `function` and `method` types to avoid duplicates):

```
--regex-JavaScript=/(,|(;|^)[ \t]*(var|let|([A-Za-z_$][A-Za-z0-9_$.]*\.)*))[ \t]*([A-Za-z0-9_$]+)[ \t]*=[ \t]*function[ \t]*\(/\5/,function-expression/
--regex-JavaScript=/(,|(;|^))[ \t]*(([A-Za-z_$][A-Za-z0-9_$.]*\.)+prototype\.)[ \t]*([A-Za-z0-9_$]+)[ \t]*=[ \t]T*function[ \t]*\(/\4\5/,prototype-method/
--regex-JavaScript=/(,|^|\*\/)[ \t]*([A-Za-z_$][A-Za-z0-9_$]+)[ \t]*:[ \t]*function[ \t]*\(/\2/,object-method/
--regex-JavaScript=/function[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)[ \t]*\([^)]*\)/\1/,function-declaration/
```

**Comment by xndcn** [comment]
@brettz9 Awesome!!!!! Thank you very much!

**Comment by brettz9** [comment]
Glad you liked it! Would you like me to add the additionally discussed entries? They seem to be working nicely on my end. My PR was only for the items mentioned in the first post...

**Pull request merged**
