### PR TITLE
Quickly added the possibility to keep display prefs in settings with …

### PR DESCRIPTION
**Pull request by Zmaon**
…a "AutoHideTypes" that allows to specify what types should be hidden by default.

### CODE REVIEW

**Comment by alexweber** [comment]
:+1:

**Comment by xndcn** [comment]
@Zmaon Awesome! Thank you very much!

**Comment by Zmaon** [comment]
@xndcn Glad it's ok for you,I was definitely missing this feature :)

**Comment by brettz9** [comment]
Can I ask:

How should one format multiple types here to hide? Does the example "variable class" mean that these are two types that can be hidden by default? Are they supposed to be in quotes when entered via Settings? Should this not be working with custom ctypes too?

**Pull request merged**
