### PR TITLE
Add Keyboard navigation

### PR DESCRIPTION
**Pull request by nikolaiborisik**
Keyboard shortcuts to navigate between tags and collapsing

### CODE REVIEW

**Comment by xndcn** [comment]
@n1k0laj Amazing work, thank you! But I found the tree-view will lose focus as soon as I press any key... Do you have this problem?

**Comment by n1k0laj** [comment]
@xndcn I didn't have this problem. I have checked on mac Version 0.192.0 and 0.188.0 with vim-mode and without. In latest commit i have changed focus from tree view to symbol-tree-view, that allow focus full panel. Did you try switch on autoFocus  option?

**Comment by xndcn** [comment]
@n1k0laj I just tried the latest commit with `auto focus` option on `Linux`, but I still have this problem... When the tree-view focused, I can press 'j' or 'k' to move the selected tag, but then it will lose focus immediately, so it can't handle key press anymore...

**Comment by n1k0laj** [comment]
@xndcn I can't reproduce on Ubuntu 14.10 with atom without additional plugins. Did you try arrows keys to navigate and  left and right arrows to toggle children. Could  you please try disable custom bindings and plugins, or provide your config with plugin list. I will try reproduce.

**Pull request closed without merging**
