### PR TITLE
Fix Atom API compliance for getScrollTop()

### PR DESCRIPTION
**Pull request by hongquan**
Should be `TextEditorElement::getScrollTop`.

### CODE REVIEW

**Comment by nicolashainaux** [comment]
Similar or same as my PR (#151), but yours looks better.

**Comment by hongquan** [comment]
Thanks @nicolashainaux. I was not aware of your PR (If I was, I won't make mine).

**Comment by nicolashainaux** [comment]
No problem, especially since yours looks better (I am not really aware of coffee script best practices, but the way you wrote it looks better). If the corrections are exactly the same, I could withdraw my PR (don't know if it is possible).

**Comment by nicolashainaux** [comment]
I closed my PR, included your patch in my [forked repo](https://github.com/nicolashainaux/symbols-tree-nav).

**Comment by xndcn** [comment]
@hongquan Thank you very much!

**Pull request merged**
