### PR TITLE
Fix for 6 deprecations on master.

### PR DESCRIPTION
**Pull request by nicolashainaux**
Would allow to close issues #139, #141, #142, #143 and #144

### CODE REVIEW

**Comment by nicolashainaux** [comment]
Integrated in both https://atom.io/packages/symbols-tree-nav and https://atom.io/packages/symbols-tree-view-fix

**Comment by xndcn** [comment]
@nicolashainaux Thank you very much for your work! Sorry for my late reply, it is too busy for me these day...

**Comment by nicolashainaux** [comment]
@xncdn No problem.

If you have more time later, you can take all or some of the enhancements that are experimental in symbols-tree-nav.

**Comment by nicolashainaux** [comment]
@xncdn Also now you can close the issues related to this PR.

**Pull request closed without merging**
